### ISSUE TITLE
[NOTICE] Open Source version deprecated

### ISSUE THREAD

**Issue by ridv** [paypal/katbox#10]
For anyone looking into this project, the open source version has ceased development. 

If I could, I would archive this project but I'm no longer with PayPal and therefore no longer have any way of asking for this project to be archived.

**Comment by ridv** [comment]
cc @lenhattan86 or @misho-kr, I'd be super grateful if you could ask for this project to be archived.

**Comment by devchristina** [comment]
Closing this issue for Archive workflow
